---
abstract: 'Perl extension for FIDE Rating List'
author:
  - 'Roman M. Parparov <roman@parparov.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chess-FIDE
provides:
  Chess::FIDE:
    file: lib/Chess/FIDE.pm
    version: 1.11
  Chess::FIDE::Player:
    file: lib/Chess/FIDE/Player.pm
    version: 1.10
requires:
  Archive::Zip: 0
  Archive::Zip::MemberRead: 0
  IO::File: 0
  IO::Scalar: 0
  LWP::UserAgent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.11
